name: CD Pipeline MODERNO

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-test:
    name: Build & Test (CI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install & Build Server
        run: |
          cd server && npm ci && npm run build
          
      - name: Install & Build Client
        run: |
          cd client && npm ci && npm run build

  deploy-production:
    name: Deploy to Production
    needs: build-and-test
    if: github.ref == 'refs/heads/development'
    environment: 
      name: production
      url: ${{ vars.PROD_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Deploy via SSH (Rolling Update)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |

            cd /tugasakhirinkubasi2026/
            git pull origin main
            
            docker-compose -f docker-compose.prod.yml up -d db
            sleep 10
            docker-compose -f docker-compose.prod.yml run --rm server sh -c "npx typeorm migration:run -d dist/data-source.js"
            
            docker-compose -f docker-compose.prod.yml build
            docker-compose -f docker-compose.prod.yml up -d --no-deps server
            docker-compose -f docker-compose.prod.yml up -d --no-deps client

      - name: Health Check Production
        run: |
          sleep 15
          curl -f ${{ vars.PROD_URL }} || exit 1
